### ISSUE TITLE
How can I re-implement the step signal results in the paper?

### ISSUE THREAD

**Issue by hanyaqi9809** [taliegemen/Neural-Network-Adaptive-PID-Controller#2]
The sine signal results is perfect. But when I just change the input signal to a step signal. The results is not consistent with paper. The settings of my step signal is as shown in the image below. How can I re-implement the step signal results in the paper?
![image](https://github.com/taliegemen/Neural-Network-Adaptive-PID-Controller/assets/58544266/eae988c5-d1d1-4c7a-a7ed-cb3e353fc6d2)
This is the result with above step signal.
![image](https://github.com/taliegemen/Neural-Network-Adaptive-PID-Controller/assets/58544266/bad2eff5-833b-40fd-a1ac-340ec3dbb40c)

**Comment by hanyaqi9809** [comment]
Another question: What's the input data X to train the ANN?

**Comment by taliegemen** [comment]
Hello,

First of all sorry for my late reply, I initially was going to reply the day you sent this but something came up and I unfortunately forgot about it :S

This project's input or "X" was data from our real-world Quanser VTOL experiment system. We give sine wave inputs to our system with different min and max voltages and record them together with the output of the system, later we use this data as "X". You can check our paper for a more detailed answer to this question.

For the step response part, use "ode1" as ode, and make 2 steps instead of just making one. The second step will be identical to our paper's response if I remember correctly.

Let me know if this helps, or if you have any questions.
Cheers!

**Comment by hanyaqi9809** [comment]
> Hello,
> 
> First of all sorry for my late reply, I initially was going to reply the day you sent this but something came up and I unfortunately forgot about it :S
> 
> This project's input or "X" was data from our real-world Quanser VTOL experiment system. We give sine wave inputs to our system with different min and max voltages and record them together with the output of the system, later we use this data as "X". You can check our paper for a more detailed answer to this question.
> 
> For the step response part, use "ode1" as ode, and make 2 steps instead of just making one. The second step will be identical to our paper's response if I remember correctly.
> 
> Let me know if this helps, or if you have any questions. Cheers!

`Thank you very much for your kind reply. It's very helpful. I'm a beginner of control theory. Could you mind answer me a further question? If I want to change the controlled system from VTOL to other system. Beside change the transfer function and the trained Win, Wout and bin, do I need to change the two red parameters shown in the below figure?
![image](https://github.com/taliegemen/Neural-Network-Adaptive-PID-Controller/assets/58544266/460251c1-ec20-46fa-966f-d18e476bbacc)

**Comment by taliegemen** [comment]
I don't think you need to change those, they are basically just for making the model give the correct inputs to the system. If you have some problems with your system you might want to change those and see how that affects it, but I would directly try the transfer function without touching anything but the ANN model and transfer function.
Also for ANN, directly refer to the repo given in the readme.
